import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import MultiRnage from "./MultiRange/MultiRange";
import ChangeComponantSelect from './ChangeContentSelect/ChangeContentSelect';
import DynamicCheckBox from './dynamicCheckBox/dynamicCheckBox';
import ScrollTop from './ScrollTop/ScrollTop';
import CustomDataFormat from './CustomDataFormat/CustomDataFormat';
import OnsubmitDropdown from './JS/data';
import ReactTable from './ReactTable/ReactTable';
import ReactForm from './ReactForm/ReactForm';
import DynamicSelectOption from './SelectOption/selct';
import Search from './Search/Search';
import InputWIthSearch from './InputWIthSearch/InputWIthSearch';
import TimePicker from './TImePicker/TimePicker';
import TextTOSpeech from './TextTOSpeech/TextTOSpeech';
import AddDynamicInput from './DynamicInput/DynamicInput';
import Routing from './Routing/Routing';
import ColorGenerator from './ColorGenerator/ColorGenerator';
import InputTextCounter from './InputTextCounter/InputTextCounter';
import ImageBlob from './ImageBlob/ImageBlob';
import DatePickerDisable from './DatePickerDisable/DatePickerDisable';
import CursorEffect from './CursorEffect/CursorEffect';
import DynamicTable from './DynamicTable/DynamicTable';
import SignIn from './googleSignin/signIn';
import DynamicTwoInput from './DynamicTwoInput/DynamicTwoInput';
import CustomPagination from './CustomPagination/CustomPagination';
import OtpGenerator from './OtpGenerator/OtpGenerator';
import SignaturePad from './SignaturePad/SignaturePad';
import Learning from './Learning/Learning';
import MultiColorRange from './MultiColorRange/MultiColorRange';
import BrowserNotification from './BrowserNotification/BrowserNotification';
import BarCodeGenerate from './BarCodeGenerator/BarCodeGenerate';
import GetCurrentAddress from './GetCurrentAddress/GetCurrentAddress';
import PreventReload from './HtmlEditor/HtmlEditor';
import CanvasImage from './HtmlEditor/HtmlEditor';
import HtmlEditor from './HtmlEditor/HtmlEditor';
import PostCall from './PostCall/PostCall';
import Noification from './Noification/Noification';
import Progress from './Progress/Progress';
import SessionStorage from './SessionStorage/SessionStorage';
import DrawingPad from './DrawingPad/DrawingPad';
// import ScrollWithProgress from './ScrollWithProgress/ScrollWithProgress';
import AddandRemoveClass from './AddandRemoveClass/AddandRemoveClass';
import Parent from './ReactMemo/Parent';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
    <Parent />
);